name: Publish Packages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Install dependencies
        run: pnpm install --force

      - name: Build packages
        run: pnpm build --filter='./packages/*'

      - name: Publish packages
        run: |
          for package in $(ls packages); do
            if [ "$package" != "continuum" ]; then
              cd packages/$package
              pnpm version patch
              git add .
              git commit -m "chore: release $package"
              git push --follow-tags
              pnpm publish --no-git-checks
              cd ../..
            fi
          done
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}